spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management
spring.datasource.username=postgres
spring.datasource.password=Prime,25i

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=anishshekhar1050@gmail.com
spring.mail.password=vqrh wlrj izdy nyse

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG

spring.web.resources.static-locations=file:uploads/
spring.web.resources.add-mappings=true

# Razorpay
razorpay.key.id=rzp_test_SwHbDd6HGT7QbE
razorpay.key.secret=KhkkI4z5rrdROGF1QHt8T417